# Generated by Django 4.0.2 on 2022-07-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=12)),
                ('leader_name', models.CharField(max_length=22)),
                ('leader_roll_no', models.CharField(max_length=9)),
                ('leader_thapar_email', models.CharField(max_length=50)),
                ('leader_phone_number', models.CharField(max_length=10)),
                ('teammate1_name', models.CharField(max_length=22)),
                ('teammate1_roll_no', models.CharField(max_length=9)),
                ('teammate1_thapar_email', models.CharField(max_length=50)),
                ('teammate2_name', models.CharField(max_length=22)),
                ('teammate2_roll_no', models.CharField(max_length=9)),
                ('teammate2_thapar_email', models.CharField(max_length=50)),
                ('teammate3_name', models.CharField(max_length=22)),
                ('teammate3_roll_no', models.CharField(max_length=9)),
                ('teammate3_thapar_email', models.CharField(max_length=50)),
                ('teammate4_name', models.CharField(max_length=22)),
                ('teammate4_roll_no', models.CharField(max_length=9)),
                ('teammate4_thapar_email', models.CharField(max_length=50)),
            ],
        ),
    ]
