# Generated by Django 4.0.2 on 2022-07-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteam',
            name='leader_name',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='leader_phone_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='leader_roll_no',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='leader_thapar_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate1_name',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate1_roll_no',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate1_thapar_email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
