# Generated by Django 4.0.2 on 2022-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_hackathonteam_leader_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate2_name',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate2_roll_no',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate2_thapar_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate3_name',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate3_roll_no',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate3_thapar_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate4_name',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate4_roll_no',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate4_thapar_email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
