# Generated by Django 4.0.2 on 2022-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_hackathonteam_teammate2_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteam',
            name='leader_name',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='leader_phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='leader_roll_no',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='leader_thapar_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate1_name',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate1_roll_no',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate1_thapar_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate2_name',
            field=models.CharField(blank=True, default='', max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate2_roll_no',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate2_thapar_email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate3_name',
            field=models.CharField(blank=True, default='', max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate3_roll_no',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate3_thapar_email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate4_name',
            field=models.CharField(blank=True, default='', max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate4_roll_no',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate4_thapar_email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
