# Generated by Django 4.0.2 on 2022-07-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_hackathonteam_leader_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteam',
            name='leader_phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
