# Generated by Django 4.0.2 on 2022-09-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_hackathonteam_leader_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate1_name',
            field=models.CharField(blank=True, default='', max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate1_roll_no',
            field=models.CharField(blank=True, default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='hackathonteam',
            name='teammate1_thapar_email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
